initial commit
amansethi00/atom-css pull request #1
Opened 2021-03-25 08:50 UTC by amansethi00

2021-03-26 03:55 UTC, vaishnavme commented on css/components/button.css
> +button {
Remove outline on buttons

2021-03-26 04:08 UTC, vaishnavme reviewed
Great work Aman. Only thing I think that can be improved is buttons. Everything else works perfect.

2021-03-26 04:08 UTC, vaishnavme commented on css/components/button.css
> +.btn-floating {
I think floating button is not perfect circle

2021-03-26 04:08 UTC, vaishnavme commented on css/components/button.css
> +  cursor: pointer;
- Remove outline on buttons
- Margin between buttons

2021-03-26 07:27 UTC, villdev reviewed
Good job Aman!

2021-03-26 07:27 UTC, villdev commented on index.html
> +          <img class="alert-image" src="./assets/x-mark.svg">
The close icon should ideally be a button element.

2021-03-26 07:27 UTC, villdev commented on index.html
> +          <button class="btn-primary-sm">Primary Button</button>
Padding seems a little less for `btn-primary-sm`. Maybe increase it or make it similar to other buttons.

2021-03-26 07:27 UTC, villdev commented on index.html
> +          <button class="btn-floating relative ">+</button>
Give corresponding width as well.

2021-03-26 07:27 UTC, villdev commented on index.html
> +            <div class="card-head">Header</div>
`card-head` seems to need a little bit more emphasis in all cards. Maybe slightly increase the font-weight.

2021-03-26 07:27 UTC, villdev commented on index.html
> +            <div class="card-text-overlay">
Most overlay are usually rgba values of black. This works as well though, just nit picking.

2021-03-26 07:27 UTC, villdev commented on node_modules/highlight.js/LICENSE
> +BSD 3-Clause License
Add `.gitignore` file and exclude `node_modules` directory.

2021-03-26 07:36 UTC, Dev-kunal commented
Good Job Aman..!  just a suggestion that colors used for alerts can be improved. You can take inspiration from bootstrap or similar platform.

2021-03-26 11:47 UTC, amansethi00 commented
> 
> 
> Good Job Aman..! just a suggestion that colors used for alerts can be improved. You can take inspiration from bootstrap or similar platform.

Ok will do that

2021-03-26 16:15 UTC, amansethi00 commented
> 
> 
> Great work Aman. Only thing I think that can be improved is buttons. Everything else works perfect.

Thank you for the review @vaishnavme ,I worked on your suggestions and recently made a commit for the same.I didn't remove outline from button as I think I will be more comfortable to use it that way(as it will be mostly used by me so I guess it should work fine).

2021-03-26 16:20 UTC, amansethi00 commented
> 
> 
> Good job Aman!

Thank you @villdev ,I worked on your suggestions and included them all in my recent commit,except the text overlay background color(it looks good so why to change,but next time I will surely remember to use light rgba of black :)

2021-03-30 16:44 UTC, im-rhlrvndrn requested changes

2021-03-30 16:44 UTC, im-rhlrvndrn commented on css/root.css
> +@import url("https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap");
Select a set of sizes and discard the rest

2021-03-30 16:44 UTC, im-rhlrvndrn commented on docs.html
> +              <img src="./assets//ironman.png" class="avatar-md"/>
Fix the no.of /

2021-03-30 20:40 UTC, merged